rvm:
  - 2.1.0
  - 2.4.0
script: 'bundle exec rake'
env:
  - PUPPET_VERSION=4.10.12
  - PUPPET_VERSION=5.5.3
matrix:
  exclude:
    - rvm: 2.1.0
      env: PUPPET_VERSION=5.5.3
    - rvm: 2.4.0
      env: PUPPET_VERSION=4.10.12
